//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace X3.DnnUrlManagement {
    
    
    public partial class HostEdit {
        
        /// <summary>
        /// valSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ValidationSummary valSummary;
        
        /// <summary>
        /// hfSelectedTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfSelectedTab;
        
        /// <summary>
        /// lblRedirectUnfriendly control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblRedirectUnfriendly;
        
        /// <summary>
        /// cbRedirectUnfriendly control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbRedirectUnfriendly;
        
        /// <summary>
        /// lblEnableCharacterReplacement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblEnableCharacterReplacement;
        
        /// <summary>
        /// cbCharacterReplacement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbCharacterReplacement;
        
        /// <summary>
        /// fiReplacementCharacter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl fiReplacementCharacter;
        
        /// <summary>
        /// lblReplaceSpaceWith control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblReplaceSpaceWith;
        
        /// <summary>
        /// ddlReplaceSpaceWith control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlReplaceSpaceWith;
        
        /// <summary>
        /// fiReplaceChars control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl fiReplaceChars;
        
        /// <summary>
        /// lblReplaceChars control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblReplaceChars;
        
        /// <summary>
        /// txtReplaceChars control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtReplaceChars;
        
        /// <summary>
        /// fiFindReplace control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl fiFindReplace;
        
        /// <summary>
        /// lblFindReplaceTheseCharacters control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblFindReplaceTheseCharacters;
        
        /// <summary>
        /// txtFindReplaceTheseCharacters control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtFindReplaceTheseCharacters;
        
        /// <summary>
        /// lblPageExtenstionHandling control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblPageExtenstionHandling;
        
        /// <summary>
        /// cbPageExtensionHandling control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbPageExtensionHandling;
        
        /// <summary>
        /// fiPageExtension control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl fiPageExtension;
        
        /// <summary>
        /// lblPageExtension control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblPageExtension;
        
        /// <summary>
        /// txtPageExtension control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtPageExtension;
        
        /// <summary>
        /// lblDeletedTabHandlingType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblDeletedTabHandlingType;
        
        /// <summary>
        /// rblDeletedTabHandlingType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButtonList rblDeletedTabHandlingType;
        
        /// <summary>
        /// lblForceLowerCase control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblForceLowerCase;
        
        /// <summary>
        /// cbForceLowerCase control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbForceLowerCase;
        
        /// <summary>
        /// lblRedirectMixedCase control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblRedirectMixedCase;
        
        /// <summary>
        /// cbRedirectMixedCase control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbRedirectMixedCase;
        
        /// <summary>
        /// lblSpaceEncodingValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblSpaceEncodingValue;
        
        /// <summary>
        /// rblSpaceEncodingValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButtonList rblSpaceEncodingValue;
        
        /// <summary>
        /// lblAutoAsciiConvert control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblAutoAsciiConvert;
        
        /// <summary>
        /// cbAutoAsciiConvert control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbAutoAsciiConvert;
        
        /// <summary>
        /// lblEnableCustomProviders control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblEnableCustomProviders;
        
        /// <summary>
        /// cbEnableCustomProviders control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbEnableCustomProviders;
        
        /// <summary>
        /// lblCheckForDuplicatedUrls control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblCheckForDuplicatedUrls;
        
        /// <summary>
        /// cbCheckForDuplicatedUrls control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbCheckForDuplicatedUrls;
        
        /// <summary>
        /// lblIgnoreUrlRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblIgnoreUrlRegex;
        
        /// <summary>
        /// txtIgnoreUrlRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtIgnoreUrlRegex;
        
        /// <summary>
        /// lblDoNotRewriteRegEx control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblDoNotRewriteRegEx;
        
        /// <summary>
        /// txtDoNotRewriteRegEx control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtDoNotRewriteRegEx;
        
        /// <summary>
        /// lblSiteUrlsOnlyRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblSiteUrlsOnlyRegex;
        
        /// <summary>
        /// txtSiteUrlsOnlyRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtSiteUrlsOnlyRegex;
        
        /// <summary>
        /// lblDoNotRedirectUrlRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblDoNotRedirectUrlRegex;
        
        /// <summary>
        /// txtDoNotRedirectUrlRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtDoNotRedirectUrlRegex;
        
        /// <summary>
        /// lblDoNotRedirectHttpsUrlRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblDoNotRedirectHttpsUrlRegex;
        
        /// <summary>
        /// txtDoNotRedirectHttpsUrlRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtDoNotRedirectHttpsUrlRegex;
        
        /// <summary>
        /// lblPreventLowerCaseUrlRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblPreventLowerCaseUrlRegex;
        
        /// <summary>
        /// txtPreventLowerCaseUrlRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtPreventLowerCaseUrlRegex;
        
        /// <summary>
        /// lblDoNotUseFriendlyUrlRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblDoNotUseFriendlyUrlRegex;
        
        /// <summary>
        /// txtDoNotUseFriendlyUrlRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtDoNotUseFriendlyUrlRegex;
        
        /// <summary>
        /// lblKeepInQueryStringRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblKeepInQueryStringRegex;
        
        /// <summary>
        /// txtKeepInQueryStringRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtKeepInQueryStringRegex;
        
        /// <summary>
        /// lblUrlsWithNoExtensionRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblUrlsWithNoExtensionRegex;
        
        /// <summary>
        /// txtUrlsWithNoExtensionRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtUrlsWithNoExtensionRegex;
        
        /// <summary>
        /// lblValidFriendlyUrlRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl lblValidFriendlyUrlRegex;
        
        /// <summary>
        /// txtValidFriendlyUrlRegex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtValidFriendlyUrlRegex;
        
        /// <summary>
        /// lbSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbSave;
    }
}
